// Kimiyyar Zahiri Tech Hub — app.js
const WORKER_URL = 'YOUR_WORKER_URL_HERE'; // ← Replace in Stage 6
let activeNode = null;
let showHausa  = false;

// ── NODE COLOURS BY CATEGORY ──────────────────────────
const COLOURS = {
  tech:      { background: '#EBF5FB', border: '#2E86C1', hover: { border: '#1A5276' } },
    trust:     { background: '#EAFAF1', border: '#1E8449', hover: { border: '#145A32' } },
      transform: { background: '#FEF9E7', border: '#E67E22', hover: { border: '#7D4E10' } },
        insight:   { background: '#F4ECF7', border: '#7D3C98', hover: { border: '#4A235A' } },
          finance:   { background: '#FEF9E7', border: '#E67E22', hover: { border: '#7D4E10' } }
          };

          // ── LOAD GRAPH ────────────────────────────────────────
          async function init() {
            try {
                const res  = await fetch('data/nodes.json');
                    const data = await res.json();

                        // Build Vis.js node dataset
                            const visNodes = new vis.DataSet(data.nodes.map(n => ({
                                  id:    n.id,
                                        label: n.title.length > 22 ? n.title.slice(0, 20) + '…' : n.title,
                                              title: n.summary,
                                                    color: COLOURS[n.category] || COLOURS.insight,
                                                          size:  10 + (n.leverage * 4),
                                                                font:  { size: 12, face: 'Plus Jakarta Sans', color: '#1A2942' },
                                                                      shape: 'dot',
                                                                            _raw:  n
                                                                                })));

                                                                                    // Build Vis.js edge dataset
                                                                                        const visEdges = new vis.DataSet(data.edges.map((e, i) => ({
                                                                                              id:     i,
                                                                                                    from:   e.from,
                                                                                                          to:     e.to,
                                                                                                                label:  e.label,
                                                                                                                      width:  e.width || 1,
                                                                                                                            color:  { color: '#D1E3F0', highlight: '#E67E22', hover: '#E67E22' },
                                                                                                                                  font:   { size: 9, color: '#5A7190', align: 'middle' },
                                                                                                                                        arrows: { to: { enabled: true, scaleFactor: 0.4 } },
                                                                                                                                              smooth: { type: 'curvedCW', roundness: 0.15 }
                                                                                                                                                  })));

                                                                                                                                                      // Draw the graph
                                                                                                                                                          const network = new vis.Network(
                                                                                                                                                                document.getElementById('kz-graph'),
                                                                                                                                                                      { nodes: visNodes, edges: visEdges },
                                                                                                                                                                            {
                                                                                                                                                                                    physics: {
                                                                                                                                                                                              barnesHut: {
                                                                                                                                                                                                          gravitationalConstant: -3000,
                                                                                                                                                                                                                      springLength: 150,
                                                                                                                                                                                                                                  springConstant: 0.04
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                            interaction: {
                                                                                                                                                                                                                                                                      hover: true,
                                                                                                                                                                                                                                                                                tooltipDelay: 200,
                                                                                                                                                                                                                                                                                          zoomView: true,
                                                                                                                                                                                                                                                                                                    dragView: true
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                          // Build a quick lookup map
                                                                                                                                                                                                                                                                                                                              const nodeMap = {};
                                                                                                                                                                                                                                                                                                                                  data.nodes.forEach(n => { nodeMap[n.id] = n; });

                                                                                                                                                                                                                                                                                                                                      // Click a node → open detail panel
                                                                                                                                                                                                                                                                                                                                          network.on('click', params => {
                                                                                                                                                                                                                                                                                                                                                if (params.nodes.length > 0) {
                                                                                                                                                                                                                                                                                                                                                        const node = nodeMap[params.nodes[0]];
                                                                                                                                                                                                                                                                                                                                                                if (node) openPanel(node);
                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                              // Clicked empty space — close panel
                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById('kz-panel').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                      console.error('Graph load error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById('kz-graph').innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                '<p style="padding:20px;color:#C0392B;">⚠️ Could not load nodes.json — check the file exists in the data/ folder.</p>';
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                  // ── OPEN NODE PANEL ───────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                  function openPanel(node) {
                                                                                                                                                                                                                                                                                                                                                                                                                    activeNode = node;

                                                                                                                                                                                                                                                                                                                                                                                                                      const title   = showHausa && node.title_hausa   ? node.title_hausa   : node.title;
                                                                                                                                                                                                                                                                                                                                                                                                                        const summary = showHausa && node.summary_hausa ? node.summary_hausa : node.summary;

                                                                                                                                                                                                                                                                                                                                                                                                                          // Category badge
                                                                                                                                                                                                                                                                                                                                                                                                                            const catEl = document.getElementById('panelCat');
                                                                                                                                                                                                                                                                                                                                                                                                                              catEl.textContent  = node.category.toUpperCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                catEl.className    = `panel-cat cat-${node.category}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('panelTitle').textContent   = title;
                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('panelSummary').textContent = summary;
                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById('panelMeta').textContent    =
                                                                                                                                                                                                                                                                                                                                                                                                                                          `Status: ${node.status}  ·  Leverage: ${node.leverage}/5`;

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Reset AI section
                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('aiSection').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('aiOutput').textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('aiLoading').classList.add('hidden');

                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('kz-panel').classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ── RUN AI ACTION ─────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function runAction(type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!activeNode) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                        const section = document.getElementById('aiSection');
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const loading = document.getElementById('aiLoading');
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const output  = document.getElementById('aiOutput');
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const label   = document.getElementById('aiLabel');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                section.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loading.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label.textContent  = type.toUpperCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await fetch(WORKER_URL, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  method:  'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nodeId:      activeNode.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              actionType:  type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nodeTitle:   activeNode.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nodeContext: activeNode.summary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const data = await response.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loading.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output.textContent = data.output || 'No response. Try again.';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // WhatsApp share
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const msg = encodeURIComponent(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `📚 *${activeNode.title}*\n\n${data.output.slice(0, 280)}...\n\n🔗 kimiyyarzahiri.com\n\n#KimiyyarZahiri #3MTT`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById('waShare').href = `https://wa.me/?text=${msg}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loading.classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    output.textContent = '⚠️ Could not reach the AI service. Check your Worker URL in app.js.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ── CLOSE PANEL ───────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById('panelClose').addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('kz-panel').classList.add('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ── LANGUAGE TOGGLE ───────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('langToggle').addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showHausa = !showHausa;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('langToggle').textContent = showHausa ? '🌙 English' : '🌙 Hausa';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (activeNode) openPanel(activeNode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ── START ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              init();
